import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Joshua
 */
public class DotAgentGUI extends javax.swing.JFrame {

	public static List<Double[]> output = new ArrayList<Double[]>();
	public static List<Integer> cts = new ArrayList<Integer>();
	public static List<String> xVal = new ArrayList<String>();
	public static List<String> yVal = new ArrayList<String>();
	public static List<Boolean> side1 = new ArrayList<Boolean>();
	public static List<Boolean> xDir = new ArrayList<Boolean>();
	public static List<Boolean> yDir = new ArrayList<Boolean>();
	public static List<Integer> ydIndex = new ArrayList<Integer>();
	public static List<Integer> vertIndex = new ArrayList<Integer>();
	private static boolean setLabels = true;
	private static boolean countLabels = true;

	/**
	 * Creates new form DotAgentGUI
	 */
	public DotAgentGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		setIconImage((new javax.swing.ImageIcon("Novi-Logo.png")).getImage());

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jLabel5 = new javax.swing.JLabel();

		jCheckBox1.setSelected(true);
		jCheckBox2.setSelected(true);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Dot Agent");
		setResizable(false);

		jTextField1.setToolTipText("Press ENTER to update");

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("NOVI WILDCAT MARCHING BAND DOT AGENT 2018");

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel2.setText("Selcted Set:");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0" }));

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel3.setText("First Set:");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jLabel4.setText("Save To:");

		jButton1.setText("Add Set");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Edit Set");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Delete Set");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("Clear All");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton6.setText("View Agent");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jCheckBox1.setText("Set Labels");

		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				setLabels = jCheckBox1.isSelected();
			}
		});

		jCheckBox2.setText("Count Labels");

		jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				countLabels = jCheckBox2.isSelected();
			}
		});

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
		jLabel5.setText("©Joshua Huang 2018");
		jLabel5.setToolTipText("Copyright Joshua Huang 2018");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(18, 18, 18)
										.addComponent(
												jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 167,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
								.addGroup(layout.createSequentialGroup().addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
														.createSequentialGroup().addComponent(jLabel2)
														.addGap(18, 18, 18)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField2,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 325,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(layout.createSequentialGroup()
																		.addComponent(jComboBox1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				140,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18, 18, 18).addComponent(jLabel3)
																		.addGap(18, 18, 18).addComponent(jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				105,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))))
												.addGap(18, 18, 18)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
																120, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE,
																120, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(layout.createSequentialGroup().addComponent(jCheckBox1)
												.addGap(53, 53, 53).addComponent(jCheckBox2)))
										.addGap(0, 9, Short.MAX_VALUE))))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jLabel5)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addComponent(
						jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2).addComponent(jLabel3)
						.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1))
				.addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
						.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton2))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
								layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jCheckBox1).addComponent(jCheckBox2))
										.addContainerGap())
						.addGroup(layout.createSequentialGroup().addGap(0, 58, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jButton6).addComponent(jButton4).addComponent(jButton3))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel5)))));

		pack();
	}// </editor-fold>

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// *******************************************
		// TODO add your handling code here:
		try {
			updateComboBox(Integer.parseInt(jTextField1.getText()));
		} catch (java.lang.NumberFormatException ex) {
			(new WarningMessage("Please make sure you entered the initial set correctly")).setVisible(true);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		(new SetWindow(true)).setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		boolean error = false;
		try {
			cts.get(jComboBox1.getSelectedIndex());			
		} catch (java.lang.IndexOutOfBoundsException e) {
			(new WarningMessage("This set may not have been added")).setVisible(true);
			error = true;
		}
		(new SetWindow(false)).setVisible(!error);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
		output.remove(jComboBox1.getSelectedIndex());
		cts.remove(jComboBox1.getSelectedIndex());
		side1.remove(jComboBox1.getSelectedIndex());
		xDir.remove(jComboBox1.getSelectedIndex());
		yDir.remove(jComboBox1.getSelectedIndex());
		xVal.remove(jComboBox1.getSelectedIndex());
		yVal.remove(jComboBox1.getSelectedIndex());
		ydIndex.remove(jComboBox1.getSelectedIndex());
		vertIndex.remove(jComboBox1.getSelectedIndex());
		System.out.println(jComboBox1.getSelectedIndex());
		DotAgentGUI.updateComboBox();
		} catch (java.lang.IndexOutOfBoundsException e) {
			(new WarningMessage("This set may not have been added")).setVisible(true);
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		cts.clear();
		output.clear();
		side1.clear();
		xDir.clear();
		yDir.clear();
		xVal.clear();
		yVal.clear();
		ydIndex.clear();
		vertIndex.clear();
		DotAgentGUI.updateComboBox();
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here
		// cts.add(494);
		// cts.add(503);
		try {
			FieldDiagramWindow.createAndShowGui(output, cts, Integer.parseInt(jTextField1.getText()));
		} catch (NumberFormatException e) {
			(new WarningMessage("Please make sure you entered all parameters correctly.")).setVisible(true);
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DotAgentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DotAgentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DotAgentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DotAgentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DotAgentGUI instance = new DotAgentGUI();
				instance.setVisible(true);
				DotAgentGUI.updateComboBox(0);
				
				// output = CalculationFunctions.getPoints(output, 8, Side.TWO,
				// Location.FRONT_HASH, 50, DirectionX.OUT, DirectionY.FRONT, 0,0);
			}
		});
	}

	public static void updateSets(int counts, Side side, Location loc, int line, DirectionX dx, DirectionY dy,
			double stepsx, double stepsy) {
		output = CalculationFunctions.getPoints(output, counts, side, loc, line, dx, dy, stepsx, stepsy);
	}

	private static void updateComboBox(int init) {
		int total = output.size();
		jComboBox1.removeAllItems();

		for (int i = 0; i < total+1; i++) {
			jComboBox1.addItem("" + (init + i));
		}
		if (total != 0) {
			jComboBox1.setSelectedIndex(total);
		}

	}

	public static void updateComboBox() {
		try {
			updateComboBox(Integer.parseInt(jTextField1.getText()));
		} catch (java.lang.NumberFormatException ex) {
			(new WarningMessage("Please make sure you entered the initial set correctly.")).setVisible(true);
		}
	}

	public static boolean getSetLabelState() {
		return setLabels;
	}

	public static boolean getCountLabelState() {
		return countLabels;
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton6;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	public static javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private static javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration
}
